WebApp/webapp/TransferSystem/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout

from rest_framework.urlpatterns import format_suffix_patterns 

urlpatterns = [
    # For the Website HTML View
    url(r'^$', views.Home_View.as_view(), name = 'home' ),
    
    url(r'^login/$', login, {'template_name':'login.html'}, name = 'login'),

    url(r'^logout/$', logout, {'next_page': '/'}, name = 'logout' ),

    url(r'^registered-users/$', views.Registered_Users.as_view(), name = 'registered-users'),

    url(r'^registered-users/delete/(?P<pk>\d+)/$', views.Delete_User.as_view(), name = 'delete-user'),

    url(r'^registered-users/register/$', views.Register_User.as_view(), name = 'register-user'),

    url(r'^transfered-articles/$', views.Transfered_Articles.as_view(), name = 'transfered-articles'),

    url(r'^transfered-articles/transfer/$', views.Transfer_Article.as_view(), name = 'transfer-article'),

    url(r'^transfered-articles/confirm/(?P<article_ids>[&0-9+]+)/$', views.Confirm_Article.as_view(), name = 'confirm-article'),

    url(r'^saved-articles/$', views.Saved_Articles.as_view(), name = 'saved-articles'),	

	url(r'^saved-articles/save/$', views.Save_Article.as_view(), name = 'save-article'),

	url(r'^saved-articles/modify/(?P<article_id>\d+)/$', views.Modify_Article.as_view(), name = 'modify-article'),

    url(r'^saved-articles/delete/(?P<article_id>\d+)/$', views.Delete_Article.as_view(), name = 'delete-article'),

    # For the Application's Rest API
    url(r'^api/(?P<article_id>[&0-9+]+)$', views.Process_Transfer.as_view(), name = 'process-transfer'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

WebApp/webapp/webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from webapp import views 

urlpatterns = [
    url(r'^$', views.Login_Redirect, name = 'LoginRedirect'), 
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('TransferSystem.urls', namespace = 'TransferSystem')),
    url(r'^api/', include('rest_auth.urls')),
]

WebApp/webapp/TransferSystem/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Article(models.Model):
    id = models.CharField(
        default = 0,
        primary_key = True,
        max_length = 8,
    )
    name = models.CharField(
        max_length = 100
    )
    description = models.CharField(
        max_length = 200
    )
    price = models.DecimalField(
        max_digits = 10,
        decimal_places = 2
    )
    url = models.CharField(
        max_length = 200
    )

class Transfer(models.Model):
    LOCATION = (
        ('Living Room', 'Living Room'),
        ('Kids', 'Kids'),
        ('Bedrooms', 'Bedrooms'),
        ('Office Space', 'Office Space'),
        ('Kitchen', 'Kitchen'),
    )
    article = models.ForeignKey(
        Article
    )
    user = models.ForeignKey(
        User
    )
    quantity = models.IntegerField(
        default = 0
    )
    location = models.CharField(
        max_length = 2,
        choices = LOCATION,
    )
    date = models.DateTimeField(
        auto_now_add = True
    )
    
class Log(models.Model):
    date_time = models.DateTimeField(
        auto_now_add = True
    )
    comment = models.CharField(
        max_length = 200
    )
    user = models.ForeignKey(
        User
    )

WebApp/webapp/TransferSystem/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms  import UserCreationForm
from django.core.exceptions import NON_FIELD_ERRORS
from .models import Article, Transfer

import re

class Registration_Form(UserCreationForm):
    first_name = forms.CharField(
        required = True
    )
    last_name = forms.CharField(
        required = True
    )

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2'
        )

    def save(self, commit = True):
        user = super(Registration_Form, self).save(commit = False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()

        return user

class Article_Creation_Form(forms.ModelForm):
    id = forms.CharField(
        required = True,
        max_length = 10,
        min_length = 8,
    )
    name = forms.CharField(
        required = True
    )
    price = forms.DecimalField(
        required = True
    )
    url = forms.URLField(
        required = False
    )

    def clean_id(self):
        data  = self.cleaned_data.get('id','')
        if not data:
            raise forms.ValidationError("Enter a valid article number")
        
        if data.isdigit() and len(data) == 8:
            print(data)
            return data
        else:
            data = "".join(re.findall(r"[\d']+", data))
            if data.isdigit() and len(data) == 8:
                return data
            else:
                raise forms.ValidationError("Invalid article number")
                
    class Meta:
        model = Article
        fields = (
            'id',
            'name',
            'description',
            'price',
            'url'
        )

class Transfer_Form(forms.ModelForm):
    # user =  forms.CharField(
    #     required = True
    # )
    # article = forms.CharField(
    #     required = True
    # )
    class Meta:
        model = Transfer
        fields = (
            'article',
            'user',
            'location',
            'quantity',
        )

WebApp/webapp/TransferSystem/views.py
import operator,datetime

from django.contrib.auth.models import User

from django.contrib.sessions.models import Session

from django.urls import reverse_lazy

from django.shortcuts import render, redirect, HttpResponse, get_object_or_404

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.db.models import Q

from .models import Article, Transfer, Log
from .forms import Registration_Form, Article_Creation_Form, Transfer_Form

from django.views.generic import ListView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView

from rest_framework import status
from rest_framework.views import APIView
from rest_framework.generics import ListCreateAPIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from .serializers import ArticleSerializer, TransferSerializer

# This is the Home View Class
@method_decorator(login_required, name='dispatch')
class Home_View(TemplateView):
    template_name = "TransferContents/home.html"

    def get_context_data(self, **kwargs):
        context = super(Home_View, self).get_context_data(**kwargs)

        # http://stackoverflow.com/questions/2723052/how-to-get-the-list-of-the-authenticated-users
        # active_users_count = Session.objects.filter(expire_date__gte = timezone.now()).count()
        # Counts how many registered user 
        active_users_count = User.objects.count()
        # Counts How many saved articles
        saved_articles_count = Article.objects.count()
        # Counts transfered unconfirmed article
        transfered_articles_count = Transfer.objects.count()

        # Pass in more content to be displayed in the home view
        context['page'] = 'Home'
        context['active_users_count'] = active_users_count
        context['saved_articles_count'] = saved_articles_count
        context['transfered_articles_count'] = transfered_articles_count 
        return context

# Displayes all registered user in the system
@method_decorator(login_required, name='dispatch')
class Registered_Users(TemplateView):
    template_name = "TransferContents/registered-users.html"

    def get_context_data(self, **kwargs):
        context = super(Registered_Users, self).get_context_data(**kwargs)
        context['users'] = User.objects.all()
        context['curr_user'] = self.request.user
        return context

# Register User Create Form
@method_decorator(login_required, name='dispatch')
class Register_User(CreateView):
    model = User
    template_name = "TransferContents/creation-form.html"
    form_class = Registration_Form

    # Displaying messages and information to re-use the html page
    # This allows me to customize how I output the message
    content = {
        'title' : 'User Registration Form',
        'type' : 'user_register',
        'response' : None
    }

    # Displays an error message if the form is invalid
    def form_invalid(self, form):
        self.content['response'] = ("alert-danger", form.errors)
        return redirect('TransferSystem:register-user')

    # Displays a success message if the form is valid
    def form_valid(self,form):
        form.save()
        # Creates a Log 
        user = self.request.user
        username2 = form.cleaned_data["username"]
        Log.objects.create(
            user = user,
            comment = "User " + user.username + " created user " + username2 +"."
        )
        self.content['response'] = ("alert-success","<p><strong>Success!</strong> User is succesfully created</p>")
        return redirect('TransferSystem:register-user')

    def get_context_data(self, **kwargs):
        context = super(Register_User, self).get_context_data(**kwargs)
        for key in self.content:
            context[key] = self.content[key]
        # Clear the content once transfered to context
        self.content['response'] = None
        return context

@method_decorator(login_required, name='dispatch')
class Delete_User(DeleteView):
    model = User
    template_name = "TransferContents/delete-form.html"
    success_url = reverse_lazy('TransferSystem:registered-users')

    content = {
        'type' : 'user_deletion_form',
        'title' : 'User Deletion Form',
        'response' : None
    }

    def form_invalid(self, form):
        self.content['response'] = ("alert-danger", form.errors)
        return redirect('TransferSystem:delete-user')

    def get_context_data(self, **kwargs):
        context = super(Delete_User, self).get_context_data(**kwargs)
        for key in self.content:
            context[key] = self.content[key]
        self.content['response'] = None
        return context

@method_decorator(login_required, name='dispatch')
class Transfered_Articles(ListView):
    template_name = "TransferContents/transfered-articles.html"
    
    def get_queryset(self):
        results = Transfer.objects.all()
        return results

    def get_context_data(self, **kwargs):
        context = super(Transfered_Articles, self).get_context_data(**kwargs) 
        context['results'] = self.get_queryset()
        return context

@method_decorator(login_required, name='dispatch')
class Transfer_Article(CreateView):
    model = Transfer
    # response = None
    template_name = "TransferContents/transfer-article-form.html"
    form_class = Transfer_Form
    article = None 

    content = { 
        'response' : None
    }

    def form_invalid(self, form):
        self.content['response'] = ("alert-danger", form.errors)
        return redirect('TransferSystem:transfer-article')

    def form_valid(self,form):
        form.save()
        self.content['response'] = ("alert-success","<p><strong>Success!</strong> Article is succesfully transfered!</p>")
        return redirect('TransferSystem:transfer-article')

    def get_object(self):
        query = self.request.GET.get('search-form')
        if query:
            result = Article.objects.filter(id = query)
            if not result:
                self.content['response'] = ("alert-danger","<p><strong>Not Found!</strong> Article Number does not exist!</p>")
                return None
            return result[0]
 
    def get_initial(self): 
        initial = super(Transfer_Article, self).get_initial()
        self.article = self.get_object()
        initial['user'] = self.request.user
        initial['article'] = self.article
        return initial

    def get_context_data(self, **kwargs):
        context = super(Transfer_Article, self).get_context_data(**kwargs)
        objects = self.get_object()
        context['object'] = self.article
        context['response'] = self.content['response']
        self.content['response'] = None
        return context

@method_decorator(login_required, name='dispatch')
class Confirm_Article(TemplateView):
    template_name = "TransferContents/confirm-article-form.html"
    success_url = reverse_lazy('TransferSystem:transfered-articles')

    def get_queryset(self):
        article_ids = self.kwargs['article_ids'][1:].split('&')
        results = []
        for article_id in article_ids:
            results.append(Transfer.objects.filter(id = article_id)[0])
        return tuple(results)

    def post(self, request, article_ids):
        article_ids = article_ids[1:].split('&')
        for article_id in article_ids:
            Transfer.objects.filter(id = article_id).delete()
        return redirect(reverse_lazy('TransferSystem:transfered-articles'))

    def get_context_data(self, **kwargs):
        context = super(Confirm_Article, self).get_context_data(**kwargs)
        context['transfers'] = self.get_queryset();
        return context

@method_decorator(login_required, name='dispatch')
class Saved_Articles(ListView):
    template_name = "TransferContents/saved-articles.html"
    model = Article
    # form_class = Article_Search_Form
    
    def get_queryset(self):
        query = self.request.GET.get('search-form')
        if query:
            results = Article.objects.filter(
                Q(id__icontains = query) | Q(name__icontains = query) | Q(description__icontains = query))
            return results 
    
    def get_context_data(self, **kwargs):
        context = super(Saved_Articles, self).get_context_data(**kwargs)
        context['results'] = self.get_queryset()
        return context


@method_decorator(login_required, name='dispatch')
class Save_Article(CreateView):
    model = Article
    template_name = "TransferContents/creation-form.html"
    form_class = Article_Creation_Form

    content = {
        'title' : 'Article Creation Form',
        'type' : 'save_article',
        'response' : None
    }

    def form_invalid(self, form):
        self.content['response'] = ("alert-danger", form.errors)
        return redirect('TransferSystem:save-article')

    def form_valid(self,form):
        form.save()
        self.content['response'] = ("alert-success","<p><strong>Success!</strong> Article is succesfully created</p>")
        return redirect('TransferSystem:save-article')

    def get_context_data(self, **kwargs):
        context = super(Save_Article, self).get_context_data(**kwargs)
        for key in self.content:
            context[key] = self.content[key]

        self.content['response'] = None
        return context

@method_decorator(login_required, name='dispatch')
class Modify_Article(CreateView):
    model = Article
    template_name = "TransferContents/creation-form.html"
    form_class = Article_Creation_Form

    content = {
        'title' : 'Article Creation Form',
        'response' : None
    }

    def form_invalid(self, form):
        self.content['response'] = ("alert-danger", form.errors)
        return redirect('TransferSystem:save-article')

    def form_valid(self,form):
        form.save()

WebApp/webapp/TransferSystem/templates/TransferContents/confirm-article-form.html
{% extends 'transfer-base.html' %}
{% load static %}

{% block title %}Confirm Articles{% endblock %}

{% block css %}

{% endblock %}

{% block main_content %}
<div class="row">
    <div class="col-lg-12">
            <h1 class="page-header">Confirm Transfer!</h1>
    </div>
</div>
{% if response %}
<div class="row">
    <div class="col-lg-12">
        <div class="alert {{ response.0 }}">
            {{ response.1 |safe  }}
        </div>
    </div>
</div>
{% endif %}

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row">
						{% for transfer in transfers %}
					<div class="col-lg-6">
							<div class="panel panel-info">
								<div class="panel-heading">
									<div class="row">
										<div class="col-xs-2">
	                        				<i class="fa fa-file-text-o fa-5x"></i>
	                    				</div>
	                    				<div class="col-xs-10">
	                    					<div class="col-xs-6 text-left">
	                    						<dl>
	                    							<dt>Article Name</dt>
	                    							<dd class="huge">{{ transfer.article.id }}</dd>
					                                <dt>Article Number:</dt>
					                                <dd>{{ transfer.article.id }}</dd>
					                                <dt>User:</dt>
					                                <dd>{{ transfer.user.username }}</dd>
					                            </dl>
	                    					</div>
	                    					<div class="col-xs-6 text-right">
	                    				        <dl>
	                                				<dt>Quantity:</dt>
	                                				<dd class="huge">{{ transfer.quantity }}</dd>
	                                				<dt>Price:</dt>
	                                				<dd>${{ transfer.article.price }}</dd>
	                                                <dt>Date:</dt>
	                                				<dd>{{ transfer.date }}</dd>
	                           		 			</dl>		
	                    					</div>
	                    				</div>
									</div>
								</div>

							</div>
					</div>
						{% endfor %}
				</div>
			</div>
			<div class="panel-footer text-right">
				<div class="row">
                    <div class="col-xs-12 text-right">
                        <form role="form" method="post">
                        {% csrf_token %}
                            <button type="submit" class="btn btn-warning" value="delete">Confirm</button>
                            <a class="btn btn-default" href="{% url 'TransferSystem:transfered-articles' %}">Return</a>
                        </form>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block javascript %}

{% endblock %}

WebApp/webapp/TransferSystem/templates/TransferContents/creation-form.html
{% extends 'transfer-base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}{{ title }}{% endblock %}

{% block css %}{% endblock %}

{% block main_content %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">{{ title }}</h1>
    </div>
<!-- /.col-lg-12 -->
</div>

{% if response %}
<div class="row">
    <div class="col-lg-12">
        <div class="alert {{ response.0 }}">
            {{ response.1 |safe  }}
        </div>
    </div>
</div>
{% endif %}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-green">
            <form role="form" method="post">
            {% csrf_token %}
                <div class="panel-body">
                    {% for field in form %}
                        <div class="form-group">
                            <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                            {{ field.error }}
                            {{ field|add_class:"form-control" }}
                        </div>
                    {% endfor %}
                </div>
                <div class="panel-footer text-right">
                    <button type="submit" class="btn btn-success" value="save">Save</button>
                    {% if type == 'user_register' %}
                        <a class="btn btn-default" href="{% url 'TransferSystem:registered-users' %}">Return</a>
                    {% else %}
                        <a class="btn btn-default" href="{% url 'TransferSystem:saved-articles' %}">Return</a>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
{% endblock %}

WebApp/webapp/TransferSystem/templates/TransferContents/delete-form.html
{% extends 'transfer-base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}{{ title }}{% endblock %}

{% block css %}{% endblock %}

{% block main_content %}

<div class="row">
    <div class="col-lg-12">
        {% if type == 'user_deletion_form' %}
            <h1 class="page-header">Are you sure you want to delete this user?</h1>
        {% else %}
            <h1 class="page-header">Are you sure you want to delete this Article?</h1>
        {% endif %}
    </div>
<!-- /.col-lg-12 -->
</div>

{% if response %}
<div class="row">
    <div class="col-lg-12">
        <div class="alert {{ response.0 }}">
            {{ response.1 |safe  }}
        </div>
    </div>
</div>
{% endif %}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <div class="row">
                    {% if type == 'user_deletion_form' %}
                    <div class="col-xs-3">
                        <i class="fa fa-user fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{ user.username }}</div>
                        <div>{{ user.first_name }} {{ user.last_name }}</div>
                    </div>
                    {% else %}
                    <div class="col-xs-3">
                        <i class="fa fa-file-text-o fa-5x"></i>
                    </div>
                    <div class="col-xs-9">
                        <div class="col-xs-9 text-left">
                            <dl>
                                <dt>Article Name</dt>
                                <dd class="huge">{{ object.name }}</dd>
                                <dt>Article Number:</dt>
                                <dd>{{ object.id }}</dd>
                                <dt>Description:</dt>
                                <dd>{{ object.description }}</dd>
                            </dl>
                        </div>
                        <div class="col-xs-3 text-right">
                             <dl>
                                <dt>
                                    Price:
                                </dt>
                                <dd class="huge">${{ object.price }}</dd>
                            </dl>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-xs-3">
                    </div>
                    <div class="col-xs-9 text-right">
                        <form role="form" method="post">
                        {% csrf_token %}
                            <button type="submit" class="btn btn-danger" value="delete">Delete</button>
                            {% if type.0 == 'user_deletion_form' %}
                                <a class="btn btn-default" href="{% url 'TransferSystem:registered-users' %}">Return</a>
                            {% else %}
                                <a class="btn btn-default" href="{% url 'TransferSystem:saved-articles' %}">Return</a>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
{% endblock %}

WebApp/webapp/TransferSystem/templates/TransferContents/home.html
{% extends 'transfer-base.html' %}

{% block title %}Dashboard{% endblock %}

{% block css %}{% endblock %}

{% block main_content %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Home</h1>
    </div>
<!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-users fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{ active_users_count }}</div>
                        <div>Active Users</div>
                    </div>
                </div>
            </div>
            <a href="{% url 'TransferSystem:registered-users' %}">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-bars fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{ transfered_articles_count }}</div>
                        <div>Transfered Articles</div>
                    </div>
                </div>
            </div>
            <a href="{% url 'TransferSystem:transfered-articles' %}">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-12">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-archive fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{ saved_articles_count }}</div>
                        <div>Saved Articles</div>
                    </div>
                </div>
            </div>
            <a href="{% url 'TransferSystem:saved-articles' %}">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> Area Chart Example
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Actions
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a href="#">Action</a>
                            </li>
                            <li><a href="#">Another action</a>
                            </li>
                            <li><a href="#">Something else here</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-area-chart"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-8 -->
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-book fa-fw"></i> Logs
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="list-group">
                    <a href="#" class="list-group-item">
                        <i class="fa fa-comment fa-fw"></i> New Comment
                        <span class="pull-right text-muted small"><em>4 minutes ago</em>
                        </span>
                    </a>
                    <a href="#" class="list-group-item">
                        <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                        <span class="pull-right text-muted small"><em>12 minutes ago</em>
                        </span>
                    </a>
                    <a href="#" class="list-group-item">
                        <i class="fa fa-envelope fa-fw"></i> Message Sent
                        <span class="pull-right text-muted small"><em>27 minutes ago</em>
                        </span>
                    </a>
                    <a href="#" class="list-group-item">
                        <i class="fa fa-tasks fa-fw"></i> New Task
                        <span class="pull-right text-muted small"><em>43 minutes ago</em>
                        </span>
                    </a>
                    <a href="#" class="list-group-item">
                        <i class="fa fa-upload fa-fw"></i> Server Rebooted
                        <span class="pull-right text-muted small"><em>11:32 AM</em>
                        </span>
                    </a>
                    <a href="#" class="list-group-item">
                        <i class="fa fa-bolt fa-fw"></i> Server Crashed!
                        <span class="pull-right text-muted small"><em>11:13 AM</em>
                        </span>
                    </a>
                    <a href="#" class="list-group-item">
                        <i class="fa fa-warning fa-fw"></i> Server Not Responding
                        <span class="pull-right text-muted small"><em>10:57 AM</em>
                        </span>
                    </a>
                    <a href="#" class="list-group-item">
                        <i class="fa fa-shopping-cart fa-fw"></i> New Order Placed
                        <span class="pull-right text-muted small"><em>9:49 AM</em>
                        </span>
                    </a>
                    <a href="#" class="list-group-item">
                        <i class="fa fa-money fa-fw"></i> Payment Received
                        <span class="pull-right text-muted small"><em>Yesterday</em>
                        </span>
                    </a>
                </div>
                <!-- /.list-group -->
                <a href="#" class="btn btn-default btn-block">View All Alerts</a>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel .chat-panel -->
    </div>
    <!-- /.col-lg-4 -->
</div>
{% endblock %}

{% block javascript %}
{% endblock %}